# Generated by Django 6.0.5 on 2026-05-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('estado_0', models.CharField(default='Lluvia', max_length=50)),
                ('estado_1', models.CharField(default='Sol', max_length=50)),
                ('pi_json', models.TextField(default='[0.5, 0.5]')),
                ('A_json', models.TextField(default='[[0.7, 0.3], [0.4, 0.6]]')),
                ('B_json', models.TextField(default='[[0.6, 0.3, 0.1], [0.1, 0.4, 0.5]]')),
                ('observaciones_json', models.TextField(default='[0, 1, 2]')),
                ('probabilidad_forward', models.FloatField(blank=True, null=True)),
                ('estados_viterbi_json', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Experimento',
                'verbose_name_plural': 'Experimentos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
